### ISSUE TITLE
Respect scroll view insets

### ISSUE THREAD

**Issue by dottore** [r-plus/AAPullToRefresh#1]
Tried it with an ios7 translucent navigation bar and it seams, the refresh header resets the scroll view insets to 0,0.

edit: it works very well when the scroll view insets are set on the table view, but if you use something like "automaticallyadjustscrollviewinsets" it won't work. maybe the system doesn't report the correct inset then.

**Comment by r-plus** [comment]
In that case, AAPullToRefresh insert code should put to `- (void)viewDidAppear:(BOOL)animated` method.
`automaticallyAdjustsScrollViewInsets` property did not yet adjust inset in `viewDidLoad` method.
In `viewDidAppear` method called timing, that property already apply, so AAPullToRefresh code can get scrollView's inset.

WARN: AAPullToRefresh did not provide duplicate safe for 4-direction action same time.

**Comment by dottore** [comment]
True that. Thank you!

Am Samstag, 14. Dezember 2013 schrieb r-plus :
