### ISSUE TITLE
Fix a bug about mulit Obsever

### ISSUE THREAD

**Issue by XiangqiTu** [r-plus/AAPullToRefresh#8]
<p>Fix a bug about mulit Obsever
</p>

<pre><code>
- (void)willMoveToSuperview:(UIView *)newSuperview {
    if (self.superview && newSuperview == nil) {\n
        UIScrollView *scrollView = (UIScrollView *)self.superview;
        if (self.showPullToRefresh) {
            if (self.isObserving) {
                [scrollView removeObserver:self forKeyPath:@"contentOffset"];
                [scrollView removeObserver:self forKeyPath:@"contentSize"];
                [scrollView removeObserver:self forKeyPath:@"frame"];
                self.isObserving = NO;
            }
        }
    }
}

</code></pre>

**Comment by XiangqiTu** [comment]
i have posted a issue about crashing app,but now i can't see the issue...

**Comment by r-plus** [comment]
Thanks
Fixed this issue by 447f924
